### ISSUE TITLE
Build issues 

### ISSUE THREAD

**Issue by MrSVCD** [retro16/acsi2stm#2]
I just downloaded arduino and what i could find of stm32duino, this to be precise: https://github.com/stm32duino/Arduino_Core_STM32, and I can't compile it.
It complains that it can't find libmaple_types so I think I am missing something.
How do I fix this?

**Comment by retro16** [comment]
Hi, It seems that the STM32 library changed lately.
Can you try installing the Roger Clark Melbourne version of the STM32 library, it seems to solve the compilation issue.
The steps are available here: https://github.com/rogerclarkmelbourne/Arduino_STM32/wiki/Installation
