### ISSUE TITLE
flashing <disk change> on every opperation on second SD card.

### ISSUE THREAD

**Issue by XR4x4** [retro16/acsi2stm#36]
I have an issue where when I double click on a drive partition or folder on the second SD card (drive 1) the ST's desktop flashes up "Disk Change" about 5 times then it will eventually open the drive/folder.

Trying to open a program from that sd card also gives the "Disk Change" flash before doing anything, mostly ending in a file error....

I have an STE, latest firmware for the stm32. SD card in slot 0 works fine. (I have tried multiple sd cards in slot 1) 

UPDATE: I just flashed version 2.40 & 2.44 and All is good, working perfectly with the second SD card. (Looks like this issue appeared in 3.0 and any release after it.)

**Comment by retro16** [comment]
Hi, sorry for the very long wait as I somewhat missed the notification (my bad).
Anyway, better late than never.
Firmware 4.00 should solve the issue (and many others).

Can you try 4.00 and close the issue if it works ? If it doesn't I'll probably ask for more information.

Thank you for your feedback and your help.

**Comment by XR4x4** [comment]
Issue is not present in current version (v4.0)
