### ISSUE TITLE
I must be doing something wrong... Help!

### ISSUE THREAD

**Issue by NullArgument** [retro16/acsi2stm#51]
Hello,
I am building an ACSI2STM for my Mega2 ST. I have everything wired up on a breadboard. I can upload the sketch, and the serial monitor shows the SD card as bootable. However, when I connect it to the Mega2 (using a 24-pin cable to the internal DMA port) and power it up, I receive an Invalid LUN error message. My micro SD card is a SanDisk Extreme 64Gb, imaged with Petari's HD adapted games image for TOS >= 1.04 (as is in my Mega2). Do you have any advice, or know why I would receive the Invalid LUN error?

The reason you see all the extra wiring is that I had originally wired up five readers, but I believe the computer USB port doesn't output enough amps to drive more than one, so I removed them from the breadboard.

![image](https://github.com/retro16/acsi2stm/assets/37764522/fb276d16-40be-4c02-b438-bac9c871290c)

![image](https://github.com/retro16/acsi2stm/assets/37764522/90d7c0a3-bdc0-4d50-aed5-0ea7eff1f32a)

**Comment by retro16** [comment]
Hi,
Based on your log output the symptom is very clear: The ST doesn't detect the IRQ signal. It may be a wiring issue but it may also be a logic level incompatibility.

**Comment by NullArgument** [comment]
I'll double check my wiring again, but everything looked good. All of the pins on the DB19 have corresponding pins on the internal DMA connector. Any recommendations on specific pins/paths to test?

What do you mean by a logic level incompatibility?

**Comment by retro16** [comment]
You need to check the IRQ pin (don't remember what pin it is check docs). 
Check wikipedia or something else for logic level compatibility it's difficult to explain on a small message.

**Comment by NullArgument** [comment]
You were right. It was both a wiring issue AND the IRQ line. On the internal DMA port the IRQ line is next to the RW line, which is supposed to be not connected. I had accidentally wired the IRQ line to the RW pin. I swapped it to the correct pin and it came right up!

Thank you!
