### ISSUE TITLE
Atari 520-STFM - 1024kb - ACSI2STM Compact v1.0 2023-08-24

### ISSUE THREAD

**Issue by u038265** [retro16/acsi2stm#79]
Hello,
I tried to install the firmware version 5.0d successfully.
When I restarted the computer I could not read the microsd C and D and the program to read the RTC did not start automatically.
I went back to the firmware version 5.0c when I restarted the computer everything started working normally again, the program that reads the RTC started automatically and I could read the microsd C and D.
Do you have any idea what the problem could be?
Thanks for your work.

**Comment by u038265** [comment]
![20241030_162054](https://github.com/user-attachments/assets/e673878f-f2d5-4245-8066-bfd1db6754c8)
With firmware version 5.0d I only have the screen where it finds the microsd but cannot read them.

**Comment by retro16** [comment]
Hi, 5.0d is a pre-release, and to be fair I somewhat rushed it to make PIO mode available as soon as possible. So it wasn't tested as much as other releases. It works on my computer, but who knows what happens on yours.
You can stay at 5.0c currently, 5.0d doesn't offer any major improvement for your setup.
As-is, I don't have enough information to debug what's happening on your computer with 5.0d, I would need a verbose log output for that.
BTW, I don't think you need the UltraSatan RTC tool at boot to set the clock, it's handled internally by the GemDrive driver. UltraSatan RTC compatibility in intented for ACSI users. Anyway it doesn't hurt either, so you can do as you like.

As always, thank you for your feedback, it's very valuable information to know when things fail and it helps tremendously improving the product. Future version 5.00 aims at perfection, nothing less, so I need all the feedback I can have.

**Comment by u038265** [comment]
Thank you so much.

**Comment by u038265** [comment]
Thank you so much.
Have a nice day.

**Comment by retro16** [comment]
5.0e should have fixed all issues, it was properly tested this time !

**Comment by u038265** [comment]
Thank you so much.
Have a nice day.
