### ISSUE TITLE
Gemdrive broken in Pre-release 5.0d

### ISSUE THREAD

**Issue by githubuser-user-ai** [retro16/acsi2stm#80]
Hi,

As the title says it, Gemdrive is broken.
The driver sees the sd card,, but on the desktop, opening C does nothing (no message, no window ...).

Revert to 5.0c, and everything is working nicely.

(Using ACSI2STM compact on STE TOS1.62, 1Mo)

Regards,
Christophe

**Comment by TzOk83** [comment]
I may confirm: STe TOS 1.62 or 2.06 has the same behavior. The firmware in the PIO version doesn't seem to work at all.

**Comment by retro16** [comment]
Fixed in 5.0e ! Sorry ;)

**Comment by githubuser-user-ai** [comment]
Thanks for fixing this issue.
It's working nicely.
No worry, your improvement are wonderful !
